import ErrorBoundary from '@/components/Errorboundary'
import "../globals.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Toaster } from "sonner"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ErrorBoundary> 
          {children}
          <Toaster/>
        </ErrorBoundary>
      </body>
    </html>
  )
}
